genomicsengland/GelReportModels

schemas/IDLs/MDT/MDTDeliveryProtocol.avdl, schemas/IDLs/latest/MDT/MDTDeliveryProtocol.avdl
First draft - to get feedback.
=> Definition of MDT integration protocol

README.md
From your starting directory, eg. ~/gel/:
Clone this repo
```
git@github.com:genomicsengland/GelReportModels.git
```
Clone the `java-commons-lib`
```
git clone git@github.com:opencb/java-common-libs.git
```
Clone the `biodata` `feature-improveclinical` branch
```
git clone -b feature-improveclinical git@github.com:opencb/biodata.git
```
Put this into a Dockerfile:
```
FROM ubuntu:16.04
RUN apt-get update && \
apt-get install -y build-essential python openjdk-8-jdk maven \
python-dev python-pip python-virtualenv postgresql \
postgresql-contrib libpq-dev \
libsasl2-dev libldap2-dev libssl-dev \
npm nodejs nodejs-legacy && \
npm install avrodoc -g
ENV PYTHONUNBUFFERED 1
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
RUN mkdir /gel
RUN mkdir /gel/GelReportModels
RUN mkdir …
```
=> Feature - Containerise the building of resources

README.md
Update README.md for building models python files using the docker image provided, in an interactive way
=> Update README.md for building models with docker

schemas/IDLs/org.gel.models.metrics.avro/1.0.1/GelBamMetrics.avdl
These additions are related to
https://cnfl.extge.co.uk/display/BER/Design+Document+-+Illumina+metrics+conversion
=> Feature - Illumina stats calculations additions to metrics_1_0_1

.gitignore, build.py, schemas/IDLs/org.opencb.biodata.models/1.2.0-SNAPSHOT/evidence.avdl, schemas/IDLs/org.opencb.biodata.models/1.2.0-SNAPSHOT/read.avdl, schemas/IDLs/org.opencb.biodata.models/1.2.0-SNAPSHOT/variant.avdl, schemas/IDLs/org.opencb.biodata.models/1.2.0-SNAPSHOT/variantAnnotation.avdl, setup.py
https://jira.extge.co.uk/browse/IP-223
=> IP-223 - OpenCB model python files on PyPi

protocols/catalog_variable_set/4.0.0/CancerParticipant.catalog_vs.json, protocols/catalog_variable_set/4.0.0/GermlineSample.catalog_vs.json, protocols/catalog_variable_set/4.0.0/Pedigree.catalog_vs.json, protocols/catalog_variable_set/4.0.0/RareDiseaseInterpretationStatus.catalog_vs.json, protocols/catalog_variable_set/4.0.0/TumourSample.catalog_vs.json, protocols/migration/migration_reports_3_0_0_to_reports_4_0_0.py, protocols/migration/participants.py, protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_0_0.py, setup.py
* Fix - Migration scripts (PR #101)
* Feature -Variable sets updated (PR #102)
=> new version 4.0.10

schemas/IDLs/org.gel.models.cva.avro/0.4.0-SNAPSHOT/Transactions.avdl
Enriching transactions with metadata:
* Transaction processing time
* Request details (IP, host, etc.)
* Transaction details (id, version, group, cohort, etc.)
* Stack trace for errors
@greglever 
@indikaraj
=> Feature - Enrich transactions with metadata

protocols/tests/test_util/test_generate_mock_objects.py, protocols/util/__init__.py, protocols/util/generate_mock_objects.py
[IP-351 - Reported Variant Inject Cancer](https://jira.extge.co.uk/browse/IP-351)
* Add `get_valid_reported_variant_inject_cancer_0_4_0`
* Add unit test
```
.......................................................
Ran 55 tests in 2.773s
OK
(.env) $  
```
=> IP-351 - Reported variant inject cancer generation

build.py, pom.xml, protocols/tests/test_util/test_generate_mock_objects.py, protocols/util/generate_mock_objects.py, schemas/IDLs/org.gel.models.system.avro/0.1.0-SNAPSHOT/HealthCheck.avdl
=> Feature - Model for Service Health Check 

pom.xml, schemas/IDLs/org.gel.models.cva.avro/0.4.0-SNAPSHOT/EvidenceSet.avdl, schemas/IDLs/org.gel.models.cva.avro/0.4.0-SNAPSHOT/ObservedVariant.avdl, schemas/IDLs/org.gel.models.cva.avro/0.4.0-SNAPSHOT/ReportedVariant.avdl, schemas/IDLs/org.gel.models.cva.avro/0.4.0-SNAPSHOT/Variant.avdl
that's it! biodata 1.3.0-SNAPSHOT is built in Jenkins and pushed into artifactory already
=> upgrade OpenCB biodata version to 1.3.0-SNAPSHOT

schemas/IDLs/org.gel.models.cva.avro/0.4.0-SNAPSHOT/Transactions.avdl
Feature - Modify CVA Transaction Model
==============================
* `Transaction.compressedReportedVariants` can be null
* `Transaction.requestDetails` can be null
* Each field within `RequestDetails` can be null
=> Feature - Modify CVA Transaction Model

.gitignore, build.py, pom.xml, protocols/util/generate_mock_objects.py, schemas/IDLs/org.gel.models.cva.avro/0.4.0-SNAPSHOT/EvidenceSet.avdl, schemas/IDLs/org.gel.models.cva.avro/0.4.0-SNAPSHOT/ObservedVariant.avdl, schemas/IDLs/org.gel.models.cva.avro/0.4.0-SNAPSHOT/ReportedVariant.avdl, schemas/IDLs/org.gel.models.cva.avro/0.4.0-SNAPSHOT/Variant.avdl
=> Feature - Changing opencb version to 1.2.1

protocols/migration/participants.py, protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_2_0_SNAPSHOT.py, requirements.txt, setup.py
[IP-404 - Fix migration for participant](https://jira.extge.co.uk/browse/IP-404)
* Add check for affectionStatus, if unknown then migrate to UNCERTAIN, not UNKNOWN which is not in the enum
* Add a test for this
```
(.env) GelReportModels$ ./run_tests.sh 
.......................................................................
Ran 71 tests in 2.326s
OK
(.env) GelReportModels$ 
```
=> Fix - Migration for participant

schemas/IDLs/org.gel.models.report.avro/4.2.0-SNAPSHOT/ExitQuestionnaire.avdl
The exit questionnaire in report 4.1.0 was lost in reports 4.2.0
=> Feature - Add missing Exit Questionnaire from report 4.2.0

CHANGES.md, protocols/migration/participants.py, setup.py
=> fix erroneous import + increase version

builds.json, protocols/migration/__init__.py, protocols/migration/participants.py, protocols/tests/test_migration/test_participants.py, protocols/util/dependency_manager.py
[IP-410 - Migrate participants 1.0.3 to 1.0.0](https://jira.extge.co.uk/browse/IP-410)
* Add `MigrationParticipants103To100.migrate_cancer_participant`
* Add test
```
(.env) $ ./run_tests.sh 
Ran 75 tests in 4.067s
OK
(.env) $ 
```
=> IP-410 - Migrate participants 1.0.3 to 1.0.0

protocols/protocol.py, protocols/tests/test_util/test_factories.py, protocols/util/factories/avro_factory.py, protocols/util/factories/reports_3_0_0_factories.py, resources/CodeGenerationFromGA4GH/process_schemas.py
* Mocking of complex objects (lists and maps) is now working fine! (not as before where all elements in the list were just the same)
* The code for registering custom factories is now tested and working
* Support to populate nullable fields
* Fixed a nasty bug in the avro validation for maps of records
@greglever
=> Feature - Mocked data

pom.xml, schemas/IDLs/org.opencb.biodata.models/1.3.0-SNAPSHOT/avro/variantAnnotation.avdl
* Updating the dependency in maven pom.xml
* Commiting a change to biodata models variantAnnotations.avdl
=> upgrading biodata dependency to 1.3.0-SNAPSHOT

protocols/migration/migration_reports_3_0_0_to_participant_1_0_0.py, protocols/migration/migration_reports_3_0_0_to_reports_4_0_0.py
* Fix to report event migration
* Fix to matched samples migration
=> fixes to migration in master

Dockerfile, builds.json, pom.xml, protocols/tests/test_util/test_dependency_manager.py, schemas/IDLs/org.gel.models.cva.avro/1.0.0-SNAPSHOT/Comment.avdl, schemas/IDLs/org.gel.models.cva.avro/1.0.0-SNAPSHOT/DataIntakeCancer.avdl, schemas/IDLs/org.gel.models.cva.avro/1.0.0-SNAPSHOT/DataIntakeRD.avdl, schemas/IDLs/org.gel.models.cva.avro/1.0.0-SNAPSHOT/EvidenceSet.avdl, schemas/IDLs/org.gel.models.cva.avro/1.0.0-SNAPSHOT/ObservedVariant.avdl, schemas/IDLs/org.gel.models.cva.avro/1.0.0-SNAPSHOT/ReportEvent.avdl, schemas/IDLs/org.gel.models.cva.avro/1.0.0-SNAPSHOT/Transactions.avdl, schemas/IDLs/org.gel.models.cva.avro/1.0.0-SNAPSHOT/Variant.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/AuditLog.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/ClinicalReportCancer.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/ClinicalReportRD.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/CommonInterpreted.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/CommonInterpretedCancer.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/CommonRequest.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/ExitQuestionnaire.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/InterpretationRequestCancer.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/InterpretationRequestRD.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/InterpretedGenomesCancer.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/InterpretedGenomesRD.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/MDTDeliveryProtocol.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/ReportVersionControl.avdl, setup.py
That's it 6.0.0 the version in development.
New package versions for reports and CVA.
=> increase models version to 6.0.0 + create new packages

README.md, pom.xml
* Remove unnecessary steps in maven build: pip install requirements and sphinx index update
* Update documentation with this and other matters...
=> Feature - Remove unnecessary steps in maven build and update README

builds.json
Adding CVA models back into build 6.0.0
=> add back cva models into build 6.0.0

protocols/migration/migration_reports_4_0_0_to_reports_5_0_0.py, protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_5_0_0.py
[IP-724 - Migrate IR RD from 4 to 5](https://jira.extge.co.uk/browse/IP-724)
* Add `MigrateReports400To500().migrate_interpretation_request_rd`
* Add test
Tests passing:
```
Removing intermediate container 00a3484fc90a
---> bb0f1f0399a5
Successfully built bb0f1f0399a5
root@3a4965d59380:/gel# cd GelReportModels/
root@3a4965d59380:/gel/GelReportModels# python -m unittest discover protocols 
Ran 28 tests in 3.547s
OK
root@3a4965d59380:/gel/GelReportModels# 
```
=> IP-724 - Migrate IR RD from 4 to 5

builds.json, protocols/migration/migration_reports_4_0_0_to_reports_5_0_0.py, protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_5_0_0.py, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/CommonInterpreted.avdl, schemas/IDLs/org.gel.models.report.avro/5.0.0-SNAPSHOT/CommonInterpretedCancer.avdl
[IP-732 - Fix Sample Compilation Issues](https://jira.extge.co.uk/browse/IP-732)
* Remove `org.opencb.biodata.models.variant.avro` from dependencies in `org.gel.models.report.avro` package for version `5.0.0-SNAPSHOT` in `builds.json`
* Remove import of `evidence.avdl` in `5.0.0-SNAPSHOT/CommonInterpreted.avdl` and copy the `org.opencb.biodata.models.variant.avro.VariantClassification` dependency from OpenCB
* Do the same for `5.0.0-SNAPSHOT/CommonInterpretedCancer.avdl`
Tests passing:
```
root@3e940dd6fa32:/gel/GelReportModels# python -m unittest  discover protocols                                                 
Ran 28 tests in …
```
=> IP-732 - Fix Sample Compilation Issues

protocols/migration/__init__.py, protocols/migration/migration_reports_3_0_0_to_reports_4_0_0.py, protocols/migration/participants.py, protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_0_0.py
[IP-725 - Migrate IR RD from 3 to 4](https://jira.extge.co.uk/browse/IP-725)
Tested with real data
==============
* Implement `MigrateReports3To4().migrate_interpretation_request_rd`
* Add test `test_migrate_interpretation_request_rd`
Tests passing:
```
(.env)$ python -m unittest discover protocols
Ran 28 tests in 2.710s
OK
(.env)$
```
=> IP-725 - Migrate IR RD from 3 to 4

protocols/migration/migration_reports_3_0_0_to_reports_4_0_0.py, protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_0_0.py
[IP-726 - Migrate IG RD from 3 to 4](https://jira.extge.co.uk/browse/IP-726)
=====================
Test passing on 3000 real cases
==========
* Add `MigrateReports3To4().migrate_interpreted_genome_rd`
* Add test `test_migrate_interpreted_genome_rd`
Tests passing:
```
(.env) $ python -m unittest discover protocols
Ran 28 tests in 2.708s
OK
(.env) $ 
```
=> IP-726 - Migrate IG RD from 3 to 4

protocols/migration/migration_reports_3_0_0_to_reports_4_0_0.py, protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_0_0.py
[IP-728 - Migrate CR RD from 3 to 4](https://jira.extge.co.uk/browse/IP-728)
Test passing on real cases
==============
* Add `MigrateReports3To4().migrate_clinical_report_rd`
* Add test `test_migrate_clinical_report_rd`
Tests passing:
```
(.env) $ python -m unittest discover protocols
Ran 28 tests in 2.790s
OK
(.env) $ 
```
=> IP-728 - Migrate CR RD from 3 to 4

protocols/migration/migration_reports_4_0_0_to_reports_5_0_0.py
Fixes needed for the CIP API to migrate data to send to CVA
```
Removing intermediate container 88269abc672b
---> 7f7d372ff164
Successfully built 7f7d372ff164
root@e8837c739491:/gel# cd GelReportModels/
root@e8837c739491:/gel/GelReportModels# python -m unittest discover
.................................
Ran 33 tests in 4.824s
OK
root@e8837c739491:/gel/GelReportModels# 
```
=> Fix - Fixes for CIP API migrations for CVA

CHANGES.md, builds.json, pom.xml, protocols/migration/migration_reports_3_0_0_to_participant_1_0_0.py, protocols/migration/participants.py, protocols/tests/test_migration/test_migration.py, protocols/tests/test_migration/test_migration_reports_3_0_0_to_participant_1_0_0.py, protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_0_0.py, protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_5_0_0.py, protocols/tests/test_migration/test_participants.py, setup.py
Version 6.0.2 (21st March 2018)
--------------------------------
* Migration of participants fixed for field `ageOfOnset` 
NOTE: we need to spend some time on migration testing...
=> Fix - Participants migration

CHANGES.md, build.py, pom.xml, schemas/IDLs/org.gel.models.cva.avro/1.0.0/Transactions.avdl, setup.py
Version 6.0.4 (23rd March 2018)
--------------------------------
* Transaction.avdl `TransactionStatus` having two new states `PROCESSING` and `PERSISTING`
* Transaction.avdl `TransactionStatus` has one less state `APPLIED`
=> change CVA states

CHANGES.md, pom.xml, protocols/protocol.py, protocols/tests/test_migration/test_migration.py, setup.py
* Fix error in validation when the input entity is not a dict always returned True
* Added a method `equals()` to all objects to check equality
=> Bugfix validation

protocols/migration/__init__.py, protocols/migration/migration_reports_4_0_0_to_reports_3_0_0.py, protocols/migration/migration_reports_5_0_0_to_reports_4_0_0.py, protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_3_0_0.py, protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_3_0_0.py, protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_4_0_0.py, setup.py
[IP-1384 - Migrate clinical report RD from v4 to v3](https://jira.extge.co.uk/browse/IP-1384)
=============
* Migrate clinical report RD from v4 to v3 of reports
* Add `TestMigrateReports5To400.test_migrate_rd_clinical_report`
```
Ran 121 tests in 7.122s
OK
```
=> IP-1384 - Migrate clinical report RD from v4 to v3

protocols/migration/__init__.py, protocols/migration/migration_helpers.py, protocols/migration/migration_reports_4_0_0_to_reports_3_0_0.py, protocols/migration/migration_reports_5_0_0_to_reports_4_0_0.py, protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_3_0_0.py, protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_3_0_0.py, protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_4_0_0.py, protocols/util/factories/avro_factory.py, schemas/IDLs/org.gel.models.report.avro/4.0.0/CommonInterpreted.avdl, setup.py
[IP-1383 - Migrate clinical report RD from 5 to 4](https://jira.extge.co.uk/browse/IP-1383) already approved by @priesgo in #264
=> IP-1383 - Migrate clinical report RD from 5 to 4 (#264)

schemas/IDLs/org.gel.models.report.avro/6.0.0/CommonInterpreted.avdl
* Make `GenePanel.panelIdentifier` nullable
=> Make GenePanel.PanelIdentifier nullable

protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_5_0_0.py
This answers @gerlv's question raised in https://github.com/genomicsengland/GelReportModels/pull/294#discussion_r206155291
=> Feature - Show RD EQ 4 and 5 are identical

protocols/migration/migration_helpers.py, protocols/tests/test_migration/test_migration_helpers.py
```
Removing intermediate container c729a179181a
---> 08a946212b7c
Successfully built 08a946212b7c
root@c5c0f4b65c6e:/gel# cd GelReportModels/
root@c5c0f4b65c6e:/gel/GelReportModels# python -m unittest discover
[...]
Ran 154 tests in 13.032s
OK
root@c5c0f4b65c6e:/gel/GelReportModels# 
```
=> Fix - Add missing Cancer EQ migrations

protocols/migration/migration_reports_5_0_0_to_reports_6_0_0.py, protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_6_0_0.py
* Migrate consequence types from `additionalTextualAnnotations` into ad hoc field for consequence types
=> migration of consequence types

protocols/migration/migration_reports_6_0_0_to_reports_5_0_0.py, protocols/tests/test_migration/test_migration_reports_6_0_0_to_reports_5_0_0.py
[IP-1879 - Migrate IR ID from 6 to 5](https://jira.extge.co.uk/browse/IP-1879)
===========================
```
Removing intermediate container b59420c861b8
---> 84f0f92f3e87
Successfully built 84f0f92f3e87
root@4242e4157360:/gel# cd GelReportModels/ && python -m unittest discover
[...]
Ran 162 tests in 10.919s
OK
root@4242e4157360:/gel/GelReportModels# 
```
=> *PLEASE REVIEW FIRST* IP-1879 - Migrate IR ID from 6 to 5

protocols/migration/__init__.py, protocols/migration/migration_helpers.py, protocols/migration/migration_reports_4_0_0_to_reports_3_0_0.py, protocols/migration/participants.py, protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_3_0_0.py, protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_3_0_0.py, protocols_utils/code_generation/test/protocols_test.py
[IP-1914 - Migrate IR ID from 4 to 3](https://jira.extge.co.uk/browse/IP-1879)
====================
```
Removing intermediate container 4074c8b4d00b
---> 966a1fd8be01
Successfully built 966a1fd8be01
root@7b123e9ea5a8:/gel# cd GelReportModels/ && python -m unittest discover
[...]
Ran 167 tests in 11.453s
OK
root@7b123e9ea5a8:/gel/GelReportModels# #
```
=> IP-1914 - Migrate IR ID from 4 to 3

protocols/migration/__init__.py, protocols/migration/migration_helpers.py, protocols/migration/migration_reports_4_0_0_to_reports_3_0_0.py, protocols/migration/migration_reports_4_0_0_to_reports_5_0_0.py, protocols/migration/migration_reports_5_0_0_to_reports_4_0_0.py, protocols/migration/participants.py, protocols/protocol.py, protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_3_0_0.py, protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_3_0_0.py, protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_4_0_0.py, protocols_utils/code_generation/test/protocols_test.py
[IP-1880 - Migrate IR RD from 5 to 4](https://jira.extge.co.uk/browse/IP-1880)
===========
Do not merge a test is still failing, please review, I will continue tomorrow.
Additionally:
* Using some factories to create appropriate mocked data
* Fixed an issue on validation of map fields
=> IP-1880 - Migrate IR RD from 5 to 4

protocols/migration/migration_reports_6_0_0_to_reports_5_0_0.py, protocols/tests/test_migration/test_migration_reports_6_0_0_to_reports_5_0_0.py
[IP-1929 - Migrate RD Clinical Report from 6 to 5](https://jira.extge.co.uk/browse/IP-1929)
====================
=> IP-1929 - Migrate RD Clinical Report from 6 to 5

protocols/migration/migration_reports_6_0_0_to_reports_5_0_0.py, protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_4_0_0.py, protocols/tests/test_migration/test_migration_reports_6_0_0_to_reports_5_0_0.py
[IP-1928 - Cancer Clinical Report Reverse Migration 6 to 5](https://jira.extge.co.uk/browse/IP-1928)
=> IP-1928 - Cancer Clinical Report Reverse Migration 6 to 5

protocols/migration/migration_reports_5_0_0_to_reports_4_0_0.py, protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_4_0_0.py
[IP-1926 - Migrate Interpreted Genome RD 5 to 4](https://jira.extge.co.uk/browse/IP-1926)
===============================
=> IP-1926 - Migrate Interpreted Genome RD 5 to 4

protocols/migration/migration_reports_6_0_0_to_reports_5_0_0.py, protocols/tests/test_migration/test_migration_reports_6_0_0_to_reports_5_0_0.py, schemas/IDLs/org.gel.models.report.avro/5.0.0/ExitQuestionnaire.avdl
[IP-1924 - Migrate EQ RD from 6 to 5](https://jira.extge.co.uk/browse/IP-1924)
=======================
=> IP-1924 - Migrate EQ RD from 6 to 5

protocols/migration/migration_reports_5_0_0_to_reports_4_0_0.py, protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_4_0_0.py
[IP-1990 - Migrate EQ RD from 5 to 4](https://jira.extge.co.uk/browse/IP-1990)
Nothing done btw, this will just be a convenience method...
=> IP-1990 - Migrate EQ RD from 5 to 4

protocols/migration/migration_reports_5_0_0_to_reports_4_0_0.py, protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_4_0_0.py
[IP-1986 - Cancer Clinical Report Reverse Migration 5 to 4](https://jira.extge.co.uk/browse/IP-1986)
=> IP-1986 - Cancer Clinical Report Reverse Migration 5 to 4

.travis.yml
Includes some reformatting done by travis command line tool.
=> Travis slack integration

protocols/migration/migration_helpers.py, protocols/tests/test_migration/test_migration_helpers.py
=> IP-2028: Integrate reverse migrations in migrations helper part 2

protocols/migration/migration_helpers.py, protocols/migration/migration_participant_1_1_0_to_participant_1_0_3.py, protocols/migration/migration_reports_6_0_0_to_reports_5_0_0.py, protocols/tests/test_migration/test_migration_helpers.py
[IP-2028 - Reverse migrate interpretation request cancer to v4](https://jira.extge.co.uk/browse/IP-2028)
=> IP-2028 - Reverse migrate interpretation request cancer to v4

protocols/migration/migration_helpers.py, protocols/tests/test_migration/test_migration_helpers.py
Python 2 tests passing locally:
```
Ran 235 tests in 31.185s
```
=> Feature - Migrate Cancer IR to IG latest returns v6

protocols/migration/migration_helpers.py, protocols/migration/migration_reports_300_to_participant_100.py, protocols/migration/migration_reports_300_to_reports_400.py
* Migrate workspace from IR into pedigree LDP code
* Accept an LDP code when migrating an isolated pedigree
=> Feature - Migrate workspace from IR into pedigree

protocols/migration/base_migration.py, protocols/migration/migration_participant_100_to_participant_103.py, protocols/migration/migration_participant_100_to_reports_300.py, protocols/migration/migration_participant_110_to_participant_100.py, protocols/migration/migration_reports_300_to_participant_100.py, protocols/tests/test_migration/test_round_trip_reports.py
* Fix bug in forward migration of severities
* Fix bug in backward migration of all modifiers
=> ensure that round trip migration of HPO modifiers work properly

CHANGES.md, pom.xml, setup.py
Doing this into develop this time, and then will make a PR develop -> master
=> Update versions to 7.1.7

schemas/IDLs/org.gel.models.cva.avro/1.1.0/ReportEvent.avdl
Updates tiering name in agreement with CIPAPI
=> Feature - Update tiering name to agree with CIPAPI

schemas/IDLs/org.gel.models.cva.avro/1.1.0/DataIntake.avdl
It should have matched type from CancerExitQuestionnaire
=> IP-2098 - Fix type in cva models

pom.xml, schemas/IDLs/org.gel.models.cva.avro/1.1.0/DataIntake.avdl, setup.py
Required to augment payload received by CVA.
=> Release 7.1.16

schemas/IDLs/org.gel.models.cva.avro/1.1.0/EvidenceSet.avdl
So that  we can populate as per https://github.com/genomicsengland/cancer-phamacogenomics-data-example.
=> Add pharmacogenomics modifications to evidences 

CHANGES.md, pom.xml, setup.py
Updates the version numbers and changelog
=> Release v7.1.17

pom.xml, protocols/migration/migration_helpers.py, protocols/migration/migration_reports_600_to_reports_601.py, protocols/tests/test_migration/test_migration_helpers.py, setup.py
* * Fixed problem with IR migration to latest
* * fixed broken tests
* changed fix version
=> FIX - IR migration to latest (#433)

protocols/migration/migration_reports_300_to_reports_400.py, protocols/tests/test_migration/test_migration_reports_300_to_reports_400.py, protocols/tests/test_migration/test_migration_reports_400_to_reports_500.py, protocols/tests/test_migration/test_migration_reports_500_to_reports_600.py, setup.py
[IP-2650 - Fix HGNC symbol migration issue](https://jira.extge.co.uk/browse/IP-2650)
============================
--------------------------------
* Add hgnc migration to `_migrate_report_event` in `migration_reports_300_to_reports_400.py`
* Add additional test to `test_migration_reports_300_to_reports_400.py` to check the correct hgnc migration
* Add additional test to `test_migration_reports_400_to_reports_500.py` to check the correct hgnc migration
* Add additional test to `test_migration_reports_500_to_reports_600.py` to check the correct hgnc migration
=> IP 2650 - Fix hgnc symbol migration

pom.xml, protocols/migration/migration_reports_601_to_reports_600.py, schemas/IDLs/org.gel.models.report.avro/6.0.1/ExitQuestionnaire.avdl, setup.py
* Additional finding is now `typed` and the description can be a string
* There are 2 new answers in the case level questions
=> IP-2800 - This fixes reported issues with the Cancer EQ

pom.xml, protocols/migration/migration_reports_601_to_reports_600.py, schemas/IDLs/org.gel.models.report.avro/6.0.1/ExitQuestionnaire.avdl, setup.py
* fixed issues withe Cancer EQ:
* Additional finding is now `typed` and the description can be a string
* There are 2 new answers in the case level questions
* added check for no small variant in back migration
* fixed bug
* fixed bug in migration
=> IP-2800 - This fixes reported issues with the Cancer EQ (#437)

pom.xml, protocols/migration/migration_reports_600_to_reports_500.py, schemas/IDLs/org.gel.models.report.avro/6.0.1/ExitQuestionnaire.avdl, setup.py
* Fixed problem with migration in cancer reportEvents
* Added new options to PGX EQ questions
=> IP-3042 - This fixed the problem with the migration failing and PGX EQ

pom.xml, protocols/catalog_variable_set/v7.3/Pedigree.catalog_vs.json, protocols/catalog_variable_set/v7.3/Referral.catalog_vs.json, protocols/catalog_variable_set/v7.3/TumourSample.catalog_vs.json, schemas/IDLs/org.gel.models.participant.avro/1.2.0/CancerParticipant.avdl, schemas/IDLs/org.gel.models.participant.avro/1.2.0/CommonParticipant.avdl, schemas/IDLs/org.gel.models.participant.avro/1.2.0/Ngis.avdl, schemas/IDLs/org.gel.models.participant.avro/1.2.0/RDParticipant.avdl, setup.py
Merge and release if you are happy with it.  - I have called the new field testConsent, as it is the consent for A particular test) and we should avoid references to GMS in this models, at some point we will change the name of the GMSConsent model too, I did not do it now to avoid confusion.
=> Added GMS (testConsent) to the cancer and rd participant models

.gitlab-ci.yml, m2_settings.xml, pom.xml
This breaks our dependence on UK cloud for builds on gitlab.
=> Gitlab mvn settings

pom.xml, protocols/migration/migration_reports_600_to_reports_500.py, setup.py
* This fixed a bug in the migration of Cancer interpretated Genome, from
5.0.0 to 6.0.0
* fixes bug when there are variants
=> IP-3318 (#467)

schemas/IDLs/org.gel.models.metrics.avro/1.2.1/FamilySelection.avdl, setup.py
A new metrics variable set `FamilySelection` for the purpose of storing results from the Family Selection process in Rare Disease pipeline.
Akin to the `ReportedVsGeneticChecks` variable set.
Added to the `1-2-1` metrics version.
=> BERTHA-3541 Family Selection result model

builds.json, pom.xml, protocols/resources/builds.json, schemas/IDLs/org.gel.models.participant.avro/1.1.2/CancerParticipant.avdl, schemas/IDLs/org.gel.models.participant.avro/1.1.2/CommonParticipant.avdl, schemas/IDLs/org.gel.models.participant.avro/1.1.2/ParticipantSensitiveInformation.avdl, schemas/IDLs/org.gel.models.participant.avro/1.1.2/RDParticipant.avdl, schemas/IDLs/org.gel.models.participant.avro/1.1.2/RDParticipantChangeLog.avdl, schemas/IDLs/org.gel.models.participant.avro/1.1.2/VersionControl.avdl, setup.py
- diseaseType is not a enumeration anymore but a string
- added version 1.1.2 for participants
- build 7.2 uses now participants 1.1.2
=> Disease Type From Enum to String

builds.json, pom.xml, protocols/resources/builds.json, schemas/IDLs/org.gel.models.participant.avro/1.1.2/CancerParticipant.avdl, schemas/IDLs/org.gel.models.participant.avro/1.1.2/CommonParticipant.avdl, schemas/IDLs/org.gel.models.participant.avro/1.1.2/ParticipantSensitiveInformation.avdl, schemas/IDLs/org.gel.models.participant.avro/1.1.2/RDParticipant.avdl, schemas/IDLs/org.gel.models.participant.avro/1.1.2/RDParticipantChangeLog.avdl, schemas/IDLs/org.gel.models.participant.avro/1.1.2/VersionControl.avdl, setup.py
* diseaseType is not a enumeration anymore but a string
* changed version control
=> Disease Type From Enum to String (#484)

schemas/IDLs/org.gel.models.report.avro/6.1.0/CommonInterpreted.avdl
This solves CIPAPI-311. As requested by cardioClassifer team.
=> feat(ACMG): Added activation strength to ACMG classification

build.py, protocols/util/dependency_manager.py, protocols_utils/utils/abstract_migration_test_real_data.py, setup.py
It seems unimportant and is currently breaking multiple builds
=> CZFE-1123: remove usage of ujson 

pom.xml, schemas/IDLs/org.gel.models.metrics.avro/1.2.1/FamilySelection.avdl, schemas/IDLs/org.gel.models.metrics.avro/1.2.1/ReportedVsGenetic.avdl, setup.py
- Add reviewed karyotype to reported vs genetic checks
- Added jira id link to reported vs genetic checks
- Add link from family selection to reported vs genetic checks annotations
=> BERTHA-4287 Update for ReportedVsGenetic and FamilySelection models

pom.xml, schemas/IDLs/org.gel.models.metrics.avro/1.2.1/FamilySelection.avdl, schemas/IDLs/org.gel.models.metrics.avro/1.2.1/ReportedVsGenetic.avdl, setup.py
Rebased from develop to master
=> BERTHA-4287 Add reviewed karyotype

README.md, builds.json, pom.xml, schemas/IDLs/org.gel.models.cva.avro/1.5.0/Comment.avdl, schemas/IDLs/org.gel.models.cva.avro/1.5.0/CvaEvidence.avdl, schemas/IDLs/org.gel.models.cva.avro/1.5.0/CvaVariant.avdl, schemas/IDLs/org.gel.models.cva.avro/1.5.0/DataIntake.avdl, schemas/IDLs/org.gel.models.cva.avro/1.5.0/ObservedVariant.avdl, schemas/IDLs/org.gel.models.cva.avro/1.5.0/ReportEvent.avdl, schemas/IDLs/org.gel.models.cva.avro/1.5.0/Transactions.avdl, setup.py
For VariantInterpretationLogInject
=> Merge develop into master to release version 7.4.0

pom.xml, schemas/IDLs/org.gel.models.report.avro/6.1.0/ClinicalReport.avdl, setup.py
Adds additional findings clinical report (being separate from primary findings it lacked a unique identifier)
Bumps version from 7.4.2 -> 7.4.3
=> feat: adds additional findings clinical report model

schemas/IDLs/org.gel.models.report.avro/6.2.0/CommonInterpreted.avdl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/genomicsengland/gelreportmodels/522)
=> fix: add missing activation strength enums

schemas/IDLs/org.gel.models.report.avro/6.2.0/VariantInterpretationLog.avdl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/genomicsengland/gelreportmodels/523)
=> feat: add pending enum to variantvalidation

protocols/migration/migration_reports_611_to_reports_620.py, protocols/tests/test_migration/test_migration_reports_611_to_reports_620.py, schemas/IDLs/org.gel.models.report.avro/6.2.0/CommonInterpreted.avdl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/genomicsengland/gelreportmodels/524)
=> fix: typo bening -> benign

protocols/migration/migration_reports_611_to_reports_620.py, protocols/tests/test_migration/test_migration_reports_611_to_reports_620.py, schemas/IDLs/org.gel.models.report.avro/6.2.0/CommonInterpreted.avdl, schemas/IDLs/org.gel.models.report.avro/6.2.0/VariantInterpretationLog.avdl
Addresses https://jira.extge.co.uk/browse/GRM-31 and https://jira.extge.co.uk/browse/GRM-34
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/genomicsengland/gelreportmodels/525)
=> Grm 34/vil comments field

protocols/migration/migration_reports_611_to_reports_620.py, protocols/tests/test_migration/test_migration_reports_611_to_reports_620.py, schemas/IDLs/org.gel.models.report.avro/6.2.0/CommonInterpreted.avdl, schemas/IDLs/org.gel.models.report.avro/6.2.0/VariantInterpretationLog.avdl
https://jira.extge.co.uk/browse/GRM-23
https://jira.extge.co.uk/browse/GRM-27
https://jira.extge.co.uk/browse/GRM-25
https://jira.extge.co.uk/browse/GRM-36
https://jira.extge.co.uk/browse/GRM-47
https://jira.extge.co.uk/browse/GRM-49
https://jira.extge.co.uk/browse/GRM-51
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/genomicsengland/gelreportmodels/528)
=> Add VIL support for other variant types

pom.xml, protocols/migration/migration_participant_120_to_participant_130.py, setup.py
There was a bug with one of the migration causing RD cases to fail as they don't have CancerParticipant
=> fix: migration bug

builds.json, pom.xml, protocols/migration/migration_reports_611_to_reports_620.py, protocols/resources/builds.json, protocols/tests/test_migration/test_migration_reports_611_to_reports_620.py, protocols/tests/test_util/test_dependency_manager.py, protocols/util/dependency_manager.py, schemas/IDLs/org.gel.models.cva.avro/1.5.2/Comment.avdl, schemas/IDLs/org.gel.models.cva.avro/1.5.2/CvaEvidence.avdl, schemas/IDLs/org.gel.models.cva.avro/1.5.2/CvaVariant.avdl, schemas/IDLs/org.gel.models.cva.avro/1.5.2/DataIntake.avdl, schemas/IDLs/org.gel.models.cva.avro/1.5.2/ObservedVariant.avdl, schemas/IDLs/org.gel.models.cva.avro/1.5.2/ReportEvent.avdl, schemas/IDLs/org.gel.models.cva.avro/1.5.2/Transactions.avdl, schemas/IDLs/org.gel.models.report.avro/6.2.0/ClinicalReport.avdl, schemas/IDLs/org.gel.models.report.avro/6.2.0/CommonInterpreted.avdl, schemas/IDLs/org.gel.models.report.avro/6.2.0/CommonRequest.avdl, schemas/IDLs/org.gel.models.report.avro/6.2.0/ExitQuestionnaire.avdl, schemas/IDLs/org.gel.models.report.avro/6.2.0/InterpretationRequestCancer.avdl, schemas/IDLs/org.gel.models.report.avro/6.2.0/InterpretationRequestRD.avdl, schemas/IDLs/org.gel.models.report.avro/6.2.0/InterpretedGenome.avdl, schemas/IDLs/org.gel.models.report.avro/6.2.0/MDTDeliveryProtocol.avdl, schemas/IDLs/org.gel.models.report.avro/6.2.0/ReportVersionControl.avdl, schemas/IDLs/org.gel.models.report.avro/6.2.0/VariantInterpretationLog.avdl, setup.py
All the changes in this epic branch have already been code reviewed in PRs 521 - 528. 
This is merging from epic branch into master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/genomicsengland/gelreportmodels/529)
=> Grm 38/variant int log updates
