schemas/IDLs/latest/GelBamMetrics.avdl
setup.py

Changes: 
* `CoverageSummary`:
* added field `lt15x`
* added field `gte15x`
* added field `gte30x`
* added field `gte50x`
* removed field `COSMIC30Xcov`
* field `mean` renamed to `avg`
* field `median` renamed to `med`
* field `n` renamed to `bases`
* `ExonCoverage` renamed to `ExomeCoverage`
* Added record `VariantsCoverage`

Version 3.0.4

---

README.md

Added extra commands in Dockerfile to actually create the python model files in protocols, otherwise they're not built when you run this.

Corrected Dockerfile commands in README.md

---

schemas/IDLs/org.gel.models.participant.avro/1.0.1/CancerParticipant.avdl
schemas/IDLs/org.gel.models.participant.avro/1.0.1/CommonParticipant.avdl
schemas/IDLs/org.gel.models.participant.avro/1.0.1/ParticipantSensitiveInformation.avdl
schemas/IDLs/org.gel.models.participant.avro/1.0.1/RDParticipant.avdl
schemas/IDLs/org.gel.models.participant.avro/1.0.1/RDParticipantChangeLog.avdl
schemas/IDLs/org.gel.models.participant.avro/1.0.1/VersionControl.avdl

* Add defined fields and enum values for HpoTermModifiers
* Add defined string enum values for HpoTerm.ageOfOnset
* Change Disorder.ageOfOnset a Float (representing years)
Because I've copied accross everything from  schemas/IDLs/org.gel.models.participant.avro/1.0.0 - /1.0.1 it's difficult to see the changes It's best to diff the two directories.
```
diff schemas/IDLs/org.gel.models.participant.avro/1.0.0 schemas/IDLs/org.gel.models.participant.avro/1.0.1/
diff schemas/IDLs/org.gel.models.participant.avro/1.0.0/RDParticipant.avdl schemas/IDLs/org.gel.models.participant.avro/1.0.1/RDParticipant.avdl
32c32
<     Age of onset in months
---
>     Age of onset in years
34c34
<     union {null, string} ageOfOnset;
---
>     union {null, float} ageOfOnset;
36a37,54
> enum Laterality {RIGHT, …
```

Update RD Participant Model to better reflect LabKey

---

pom.xml

Due to the changes introduced in PR #86 `mvn clean install -DskipTests` will fail.
This fixes the issue.

Fix - Add models parameter to pom.xml

---

protocols/protocol.py
protocols/tests/test_protocol.py

* Adds non-breaking change: `debug=False` default parameter to the `ProtocolElement.validate` method
* Tests this in `protocols/tests/test_protocol.py` with the following:
- Gets a valid `ReportedSomaticStructuralVariants` object
- Changes `variant.reportedStructuralVariantCancer.end` to `None`
- Runs `validate` with the new `debug` parameter set to `True`
- Checks for the presence of the error messages such as: `Class: ReportedStructuralVariantCancer expects field: end with schema type: "int" but received value: None`
Open to ideas for clearer messages or a better way to implement this ! :smile: 
Running Locally:
```
(.env) $ python -m unittest discover protocols
.....
Ran 5 tests …
```

Feature - Add debug parameter to protocols.validate

---

resources/CodeGenerationFromGA4GH/process_schemas.py

Increasing the line width from the standard 70 to 100 when calling `textwrap.wrap` makes sure that we don't end up with a dash character at the end of a line in a schema string in the python files after they're converted from avro.
We need a more robust solution to this in the future.
After running `python build.py` we can now import models from `protocols.cva`:
```
In [1]: from protocols.cva_0_3_1 import TieredVariantInjectRD
In [2]: from protocols.cva_0_3_1 import ReportedVariantInjectRD
In [3]: from protocols.cva_0_3_1 import EvidenceEntry
In [4]: new_evidence_entry = EvidenceEntry()
In [5]: new_evidence_entry.validate_parts()
Out[5]: 
{u'additionalProperties': [],
u'alleleOrigin': True,
u'bibliography': [],
u'confidence': True, …
```

Feature - Change line length for schema string

---

build.py

Currently in jenkins we use:
```
python build.py --models org.ga4gh.models::3.0.0 org.gel.models.participant.avro::1.0.0 org.gel.models.participant.avro::1.0.1 org.gel.models.participant.avro::1.0.2 org.gel.models.metrics.avro::1.0.0 org.gel.models.metrics.avro::1.0.1  org.gel.models.report.avro::2.1.0 org.gel.models.report.avro::3.0.0 org.gel.models.report.avro::3.1.0 org.gel.models.report.avro::4.0.0 org.gel.models.cva.avro::0.3.1
```
which is annoyingly long to keep track of and add to as we have additional models....
Let's keep them in `build.py` instead.

Feature - Build all models by default

---

protocols/protocol.py
protocols/tests/test_util/test_generate_mock_objects.py
protocols/util/generate_mock_objects.py

[IP-248 Generate InterpretationRequest (RD) objects](https://jira.extge.co.uk/browse/IP-248)
===========================
* Interpretation Request RD generation for 2.1, 3.0, 3.1 and 4.0 models
* Tests for each
```
...................
Ran 19 tests in 0.034s
OK
(.env) $
```

IP-248 - Generate Valid Interpretation Request objects

---

protocols/tests/test_util/test_generate_mock_objects.py
protocols/util/generate_mock_objects.py

[IP-247 Generate InterpretedGenome (Cancer) objects](https://jira.extge.co.uk/browse/IP-247)
===========================
* Cancer Interpreted Genome generation for 2.1, 3.0, 3.1 and 4.0 models
* Tests for each
```
.......................
Ran 23 tests in 0.040s
OK
(.env) $
```

IP-247 - Generate Interpreted Genome Cancer objects

---

protocols/tests/test_util/test_generate_mock_objects.py
protocols/util/__init__.py
protocols/util/generate_mock_objects.py

[IP-300 - Clinical Report Cancer Object Generation](https://jira.extge.co.uk/browse/IP-300)
====================
Allows the generation of valid `ClinicalReportCancer` objects in each version of the model
* Add `get_valid_clinical_report_cancer_2_1_0`, `3_1_0` and `4_0_0`
* Add tests for `get_valid_clinical_report_cancer_2_1_0`, `3_0_0`, `3_1_0` and `4_0_0`
```
...............................
Ran 31 tests in 0.283s
OK
(.env) $ 
```

IP-300 - Clinical Report Cancer Object Generation

---

protocols/tests/test_util/test_generate_mock_objects.py
protocols/util/__init__.py
protocols/util/generate_mock_objects.py

[IP-308 - Generate RD Exit Questionnaire Objects](https://jira.extge.co.uk/browse/IP-308)
====================================================
* Add `get_valid_rd_exit_questionnaire_3_1_0` and `4_0_0`
* Add tests for `get_valid_rd_exit_questionnaire_3_0_0`, `3_1_0` and `4_0_0`
```
..................................
Ran 34 tests in 0.165s
OK
(.env) $ 
```

IP-308 - Generate RD Exit Questionnaire Objects

---

protocols/tests/test_util/test_generate_mock_objects.py
protocols/util/__init__.py
protocols/util/generate_mock_objects.py

[IP-311 - Clinical Report RD Object Generaton](https://jira.extge.co.uk/browse/IP-311)
===================
* Functionality for generating `ClinicalReportRD` objects at versions 2.1, 3.1 and 4.0 of the models
* Add tests for functions for versions 2.1, 3.0, 3.1 and 4.0
```
......................................
Ran 38 tests in 0.188s
OK
(.env) $ 
```

IP-311 - Clinical Report RD Object Generaton

---

protocols/migration/__init__.py
protocols/migration/migration_reports_3_0_0_to_reports_4_2_0_SNAPSHOT.py
protocols/migration/participants.py
protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_2_0_SNAPSHOT.py
protocols/tests/test_util/test_generate_mock_objects.py
protocols/util/__init__.py
protocols/util/generate_mock_objects.py

* Add `MigrateReports3To420SNAPSHOT.migrate_interpretation_request_rd` to migrate interpretation requests from version `3.0.0` to `4.2.0-SNAPSHOT`, required by the CIP API.
* Add `TestMigrateReports3To420SNAPSHOT.test_migrate_interpretation_request` to test this
```
............................................
Ran 44 tests in 2.602s
OK
(.env) $ 
```

Feature - Migrations to reports_4_2_0_SNAPSHOT

---

schemas/IDLs/org.gel.models.cva.avro/0.4.0-SNAPSHOT/ObservedVariant.avdl

Some fields in Observed Variant are not required anymore as they will be stored inside a Reported Variant always.
@indikaraj

removing unused fields from OV after merging it into RV

---

protocols/migration/migration_reports_3_0_0_to_reports_4_2_0_SNAPSHOT.py
protocols/migration/participants.py
protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_2_0_SNAPSHOT.py

[IP-346 - Migrate InterpretedGenomeRD](https://jira.extge.co.uk/browse/IP-346)
=========================
Migrate InterpretedGenomeRD from 3.0.0 to 4.2.0-SNAPSHOT as required by the CIP API to send Reported Variants to CVA 
* Add `migrate_interpreted_genome_rd` to `MigrateReports3To420SNAPSHOT`
* Add `test_migrate_interpreted_genome_rd` to `TestMigrateReports3To420SNAPSHOT`
```
..............................................
Ran 46 tests in 2.550s
OK
(.env) $ 
```

IP-346 - Migrate InterpretedGenomeRD

---

protocols/migration/migration_reports_3_0_0_to_reports_4_2_0_SNAPSHOT.py
protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_2_0_SNAPSHOT.py

[IP-347 - Migrate ClinicalReportRD](https://jira.extge.co.uk/browse/IP-347)
=======================================================
Migrate ClinicalReportRD objects to version 4.2.0-SNAPSHOT in order for the CIP API to push Candidate Variants to CVA
* Add `migrate_clinical_report_rd` to `MigrateReports3To420SNAPSHOT`
* Add `test_migrate_clinical_report_rd` to `TestMigrateReports3To420SNAPSHOT`
```
...............................................
Ran 47 tests in 2.653s
OK
(.env) $ 
```

IP-347 - Migrate ClinicalReportRD

---

build.py
pom.xml
schemas/IDLs/org.gel.models.cva.avro/0.4.0-SNAPSHOT/Variant.avdl

* Annotator and annotations version added to CVA variant model
* Optionally building only snapshots by running `build.py --build_only_snapshots`. Maven build will only build snapshots... May change in the future

IP-75 - Adding annotations and annotator version to VariantRepresentation model 

---

protocols/tests/test_util/test_generate_mock_objects.py
protocols/util/__init__.py
protocols/util/generate_mock_objects.py

[IP-353 - Candidate Variant Inject Cancer object generation](https://jira.extge.co.uk/browse/IP-353)
* Add `get_valid_candidate_variant_inject_cancer_0_4_0`
* Add unit test
```
........................................................
Ran 56 tests in 2.533s
OK
(.env) $ 
```

IP-353 - Candidate Variant Inject Cancer object generation

---

protocols/tests/test_util/test_generate_mock_objects.py
protocols/util/generate_mock_objects.py

* Reflect changes in `participant_1_0_3.CancerParticipant` when generating valid empty object
* Add test for `get_valid_cancer_participant_1_0_3`
```
.........................................................
Ran 57 tests in 3.201s
OK
(.env) $ 
```

Fix - get_valid_cancer_participant_1_0_3

---

build2.py
builds.json
protocols/tests/test_util/test_dependency_manager.py
protocols/tests/test_util/test_factories.py
protocols/util/dependency_manager.py
protocols/util/factories/avro_factory.py
protocols/util/factories/ga4gh_factories.py
protocols/util/factories/reports_3_0_0_factories.py
protocols/util/factories/reports_4_1_0_factories.py

Created a generic mock factory based on factory-boy.
Now you can create any valid mock object for any model version as follows:
```
interpretation_request_factory = GenericFactoryAvro.get_factory_avro(
protocols.reports_4_2_0.InterpretationRequestRD,
version = VERSION_430
)
instance = interpretation_request_factory()
self.assertTrue(instance.validate(instance.toJsonDict()))
```
There is also a dependency manager that reads `builds.json` and exposes useful information about versions and dependencies.
```
...........................................................................
Ran 75 tests in 2.568s
OK
(.env) $ 
```

Feature - Generic mock factory for Avro objects

---

protocols/migration/base_migration.py
protocols/migration/migration.py
protocols/migration/migration_reports_3_0_0_to_participant_1_0_0.py
protocols/migration/migration_reports_3_0_0_to_reports_4_0_0.py
protocols/migration/migration_reports_3_0_0_to_reports_4_2_0.py
protocols/migration/migration_reports_3_1_0_to_participant_1_0_0.py
protocols/migration/migration_reports_4_0_0_to_reports_4_2_0.py
protocols/migration/migration_reports_4_2_0_to_reports_4_0_0.py
protocols/migration/participants.py
protocols/tests/test_migration/test_migration_reports_3_0_0_to_participant_1_0_0.py
protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_0_0.py
protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_2_0.py
protocols/tests/test_migration/test_migration_reports_3_1_0_to_participant_1_0_0.py
protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_4_2_0.py
protocols/util/dependency_manager.py
protocols/util/singleton.py
schemas/IDLs/org.gel.models.report.avro/4.2.0-SNAPSHOT/ExitQuestionnaire.avdl

* All migrations are now using the mocked data factories
* Many issues on migration scripts arised when using this mocked data. Some of them due to nullable fields being null in the current mocked data and some others due to not having empty strings on non nullable fields.
Also several glitches migrating between different versions were identified I will report those separately.
@Antonior26 
@greglever

Feature - Migrations use mocked data factories

---

pom.xml
protocols/util/dependency_manager.py

builds.json is now copied into the protocols package when we run `mvn initialize`
@greglever

Fix - Adding builds.json as a resource to the protocols package

---

protocols/util/generate_mock_objects.py

[IP-283 - CalledGenotype.genotype validation for RD reports 2.1.0](https://jira.extge.co.uk/browse/IP-283)
* Ensure `genotype` for a `reports_2_1_0.CalledGenotype` object is not an empty string
```
(.env) GelReportModels$ ./run_tests.sh 
............................................................................
Ran 76 tests in 3.314s
OK
(.env) GelReportModels$ 
```

IP-283 - Called Genotype Validation requirements

---

Dockerfile

Feature - Remove Maven from Dockerfile
* Replace `mvn` commands with `python build2.py --skip-docs`
```
...............................
Ran 31 tests in 4.009s
OK
(.env) $ 
```
```
$ sudo ./build_models
...
---> 03c943fb28e4
Removing intermediate container 486a0d73e025
Successfully built 03c943fb28e4
```

Feature - Remove Maven from Dockerfile

---

protocols/migration/migration_reports_3_0_0_to_reports_4_2_0.py
protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_2_0.py
schemas/IDLs/org.gel.models.report.avro/4.0.0/CommonRequest.avdl
schemas/IDLs/org.gel.models.report.avro/4.2.0-SNAPSHOT/CommonRequest.avdl

[IP-428 - Modify md5sum and migration](https://jira.extge.co.uk/browse/IP-428)
======================
Summary of changes
===================
* Change `md5Sum` to be `string` instead of `File` for models v4.0.0 and v4.2.0
* Modify migrations to account for this
* Modify migration tests to make the `md5Sum` a valid `File` object for 3.0.0 and then check it is `None` following the migration.
```
[INFO] Webapp assembled in [7540 msecs]
[INFO] Building war: /gel/GelReportModels/target/gel-models-docs-4.3.0-SNAPSHOT.war
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:26 min
[INFO] Finished at: 2017-10-27T12:42:13+00:00
[INFO] Final Memory: …
```

IP-428 - Modify md5sum and migration

---

protocols/migration/migration_reports_4_0_0_to_reports_4_2_0.py
protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_4_2_0.py
setup.py

[IP-450 - Fix Migration of Cancer Clinical Report from 4.0.0 to 4.2.0](https://jira.extge.co.uk/browse/IP-450)
=============================
This currently blocks [IP-449 - Store Cancer IR, IG and CR as 4.2.0](https://jira.extge.co.uk/browse/IP-449)
* Migrate to `new_cancer_clinical_report.candidateVariants` instead of `new_cancer_clinical_report.reportedVariants` and refactor to a list comprehension
* Migrate to `new_cancer_clinical_report.candidateStructuralVariants` instead of `new_cancer_clinical_report.reportedStructuralVariants` and refactor to a list comprehension
* Add `test_migrate_cancer_clinical_report` to test_migration_reports_4_0_0_to_reports_4_2_0.py to make sure it works
``` …
```

IP-450 - Fix Cancer Clincal Report 4.0.0 to 4.2.0 migration

---

protocols/migration/migration_reports_4_0_0_to_reports_4_2_0.py
protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_4_2_0.py

[IP-450 - Fix Migration of Cancer Clinical Report from 4.0.0 to 4.2.0](https://jira.extge.co.uk/browse/IP-450)
=============================
This currently blocks [IP-449 - Store Cancer IR, IG and CR as 4.2.0](https://jira.extge.co.uk/browse/IP-449)
* Migrate to `new_cancer_clinical_report.candidateVariants` instead of `new_cancer_clinical_report.reportedVariants` and refactor to a list comprehension
* Migrate to `new_cancer_clinical_report.candidateStructuralVariants` instead of `new_cancer_clinical_report.reportedStructuralVariants` and refactor to a list comprehension
* Add `test_migrate_cancer_clinical_report` to test_migration_reports_4_0_0_to_reports_4_2_0.py to make sure it works
``` …
```

IP-450 - Fix Migration of Cancer Clinical Report from 4.0.0 to 4.2.0

---

schemas/IDLs/org.gel.models.cva.avro/1.0.0-SNAPSHOT/DataIntakeCancer.avdl
schemas/IDLs/org.gel.models.cva.avro/1.0.0-SNAPSHOT/DataIntakeRD.avdl
schemas/IDLs/org.gel.models.cva.avro/1.0.0-SNAPSHOT/EvidenceSet.avdl
schemas/IDLs/org.gel.models.cva.avro/1.0.0-SNAPSHOT/ReportEvent.avdl

The data intake for RD exit questionnaires has been refactored so we assume that exit questionnaires need to be disaggregated as follows:
* For each variant reported in a rare disease questionnaire a `ReportedVariantQuestionnaireRd` will be created.
* Family level questions will be repeated for every variant in the questionnaire
* Variant group level questions will be repeated for every variant in a group of variants
* Groups of variants will be defined in the field `ReportEventQuestionnaireRd.groupOfVariants` being the values of the group of variants only relevant within the same questionnaire.
The above format is very repetitive, but this aligns with how other report events are stored and facilitates data querying.

Feature - Refactor build of report events from questionnaires

---

builds.json
schemas/IDLs/org.gel.models.participant.avro/1.1.0-SNAPSHOT/CancerParticipant.avdl
schemas/IDLs/org.gel.models.participant.avro/1.1.0-SNAPSHOT/CommonParticipant.avdl
schemas/IDLs/org.gel.models.participant.avro/1.1.0-SNAPSHOT/ParticipantSensitiveInformation.avdl
schemas/IDLs/org.gel.models.participant.avro/1.1.0-SNAPSHOT/RDParticipant.avdl
schemas/IDLs/org.gel.models.participant.avro/1.1.0-SNAPSHOT/RDParticipantChangeLog.avdl
schemas/IDLs/org.gel.models.participant.avro/1.1.0-SNAPSHOT/VersionControl.avdl

Participants package had two redefinitions across RD and cancer models for `Sex` and `SampleSource` that were colliding. Both fields are now in `CommonParticipan.avdl`.
There is a new package version for participants `1.1.0-SNAPSHOT`

Feature - participants 1.1.0 avoid redefine Sex and SampleSource

---

protocols/migration/migration_reports_4_0_0_to_reports_5_0_0.py
protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_5_0_0.py

[IP-723 - Migrate Cancer IR from 4 to 5](https://jira.extge.co.uk/browse/IP-723)
========
Test passing with ILMN-8308-1 cancer IR
=====
* Implement `igrate_cancer_interpretation_request` in `protocols/migration/migration_reports_4_0_0_to_reports_5_0_0.py`
* Add test `test_migrate_cancer_interpretation_request`
```
(.env) $ python -m unittest discover protocols
Ran 28 tests in 2.629s
OK
(.env) $ 
```

IP-723 - Migrate Cancer IR from 4 to 5

---

CHANGES.md
builds.json
pom.xml
protocols/migration/migration_reports_4_0_0_to_reports_5_0_0.py
protocols/tests/test_migration/base_test_migration.py
protocols/tests/test_migration/test_migration_reports_3_0_0_to_participant_1_0_0.py
protocols/tests/test_migration/test_migration_reports_3_0_0_to_reports_4_0_0.py
protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_5_0_0.py
protocols/tests/test_migration/test_participants.py
protocols/util/dependency_manager.py
setup.py

* Remove hotfix version numbering from build version from 6.0 onwards. To generate any mock data from build 6.0 onwards, the string `6.0` is expected instead of `6.0.0`
* Fixed `MigrateReports400To500().migrate_cancer_interpretation_request` and `MigrateReports400To500().migrate_interpretation_request_rd` that were failing when tested with nullable fields being null. Tests are improved
* Refactored migration tests to use `_validate`

IP-916: hotfix 6.0.3

---

protocols/migration/migration_reports_5_0_0_to_reports_4_0_0.py
protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_3_0_0.py
protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_3_0_0.py
protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_4_0_0.py
setup.py

[Feature - Test migration of Clinical Report RD from v5 to v3]()
=============================
* Add test to generate mock clinical report RD in version 5, migrate to version 4 (and check it's valid) then migrate to version 3 and check it's valid.
```
Ran 122 tests in 12.296s
OK
```

Feature - Test migration of Clinical Report RD from v5 to v3

---

protocols/migration/__init__.py
protocols/migration/migration_helpers.py
protocols/migration/migration_reports_4_0_0_to_reports_3_0_0.py
protocols/migration/migration_reports_5_0_0_to_reports_4_0_0.py
protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_3_0_0.py
protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_3_0_0.py
protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_4_0_0.py
schemas/IDLs/org.gel.models.report.avro/4.0.0/CommonInterpreted.avdl
setup.py

[IP-1383 - Migrate clinical report RD from 5 to 4](https://jira.extge.co.uk/browse/IP-1383)
===============
===============
* Add `MigrateReports500To400.migrate_clinical_report_rd` within `protocols/migration/migration_reports_5_0_0_to_reports_4_0_0.py` to migrate RD Clinical Reports from version 5 of reports to version 4
* Add `test_migrate_rd_clinical_report`
* Add `test_migrate_analysis_panel`
* Add `test_migrate_genomic_entity_to_feature`
* Add `test_migrate_report_event`
* Add `test_migrate_reported_variant`
* Add `test_migrate_variant_call_to_called_genotype`
```
(.env) greg@greg-Latitude-E7470:~/gel/GelReportModels$ python -m unittest discover
Ran 120 tests in 8.246s
OK
(.env) …
```

IP-1383 - Migrate clinical report RD from 5 to 4

---

schemas/IDLs/org.gel.models.report.avro/6.0.0/CommonInterpreted.avdl

* Make `Phenotypes.standardPhenotypes` nullable
* Rename `NumberOfCopies.confidenceIntervalMaximun` to `NumberOfCopies.confidenceIntervalMaximum`
* Rename `NumberOfCopies.confidenceIntervalMinimun` to `NumberOfCopies.confidenceIntervalMinimum`
* Make `VariantCall.alleleOrigins` nullable

Proposed model changes

---

builds.json

Changes required to build the latest version of the models
* Remove `7.0` from builds.json
* Rename `7.1` to `7.0`

Change builds.json

---

protocols/migration/migration_helpers.py
protocols/migration/migration_reports_5_0_0_to_reports_6_0_0.py
protocols/tests/test_migration/test_migration_helpers.py
protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_6_0_0.py

[IP-1738 - Migrate cancer IG to v6](https://jira.extge.co.uk/browse/IP-1738)
==============
* In `migration_helpers`, `migrate_interpreted_genome_cancer_to_latest` now migrates to a v6 IG.
* Add cancer IG migrations to `migration_reports_5_0_0_to_reports_6_0_0.py`
* Modify existing tests to ensure migrated IG is v6
```
Ran 145 tests in 9.279s
OK
```
```
Removing intermediate container 3113ae655143
---> ecefa0b3c8ef
Successfully built ecefa0b3c8ef
root@f130dcd90ec0:/gel# 
```

IP-1738 - Migrate cancer IG to v6

---

protocols/migration/migration_helpers.py
protocols/migration/migration_reports_5_0_0_to_reports_6_0_0.py
protocols/tests/test_migration/base_test_migration.py
protocols/tests/test_migration/test_migration_helpers.py
protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_6_0_0.py

[IP-1765 - Migrate Cancer EQ to v6](https://jira.extge.co.uk/browse/IP-1765)
============================
===============
* Add `migrate_cancer_exit_questionnaire_to_latest` to `migration_helpers.py` which migrates cancer exit questionnaires to v6 of the models. 
*  Add migrations in `migration_reports_5_0_0_to_reports_6_0_0.py`.
* Add tests in `test_migration_helpers.py` and `test_migration_reports_5_0_0_to_reports_6_0_0.py`.
```
Ran 153 tests in 13.757s
OK
```
```
Removing intermediate container b4d388f572ae
---> 58f13836d673
Successfully built 58f13836d673
root@fc792d566f84:/gel# 
```

IP-1765 - Migrate Cancer EQ to v6

---

protocols/migration/migration_helpers.py
protocols/migration/migration_reports_5_0_0_to_reports_6_0_0.py
protocols/tests/test_migration/test_migration_helpers.py
protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_6_0_0.py

[IP-1739 - Migrate clinical report cancer to v6](https://jira.extge.co.uk/browse/IP-1739)
===================================
* `migrate_clinical_report_cancer_to_latest` in `migration_helpers` now migrates to v6
* Add tests
```
Ran 146 tests in 18.091s
OK
```
```
Removing intermediate container 61a26b457c2f
---> 4fc84c4a9d4a
Successfully built 4fc84c4a9d4a
root@b44ccee7cae1:/gel# 
```

IP-1739 - Migrate clinical report cancer to v6

---

protocols/migration/migration_helpers.py
protocols/migration/migration_reports_5_0_0_to_reports_6_0_0.py
protocols/tests/test_migration/test_migration_helpers.py
protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_6_0_0.py

[IP-1734 - Migrate clinical report rd to latest to migrate to v6](https://jira.extge.co.uk/browse/IP-1734)
===============
==============
* `migration_helpers.migrate_clinical_report_rd_to_latest` migrates to v6 of clinical report RD
* Add tests
```
Ran 141 tests in 9.738s
OK
```

IP-1734 - Migrate clinical report rd to latest to migrate to v6

---

protocols/migration/migration_helpers.py
protocols/migration/migration_reports_5_0_0_to_reports_6_0_0.py
protocols/tests/test_migration/base_test_migration.py
protocols/tests/test_migration/test_migration_helpers.py
protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_6_0_0.py

[IP-1732 - Migrate IR to IG v6](https://jira.extge.co.uk/browse/IP-1732)
=========================================
===============
* When migrating RD IRs earlier than v5 to IG, migrate to v6 og IG
* Add tests
```
Ran 142 tests in 8.912s
OK
```
```
Removing intermediate container 1cd793ea471b
---> 9679ed773f57
Successfully built 9679ed773f57
root@52a8a61b184a:/gel# 
```

IP-1732 - Migrate IR to IG v6

---

protocols/migration/migration_helpers.py
protocols/migration/migration_reports_5_0_0_to_reports_6_0_0.py
protocols/tests/test_migration/test_migration_helpers.py
protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_6_0_0.py

[IP-1736 - Migrate cancer IR to v6](https://jira.extge.co.uk/browse/IP-1736)
=================================
* When migrating cancer IR to latest, migrate to v6, which is identical to v5
* Add tests to make sure cancer IR is migrated to v6
```
Ran 142 tests in 14.117s
OK
```
```
Removing intermediate container 142fa350ac33
---> 271efd0f459e
Successfully built 271efd0f459e
root@fd9bd4270973:/gel# 
```

IP-1736 - Migrate cancer IR to v6

---

protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_6_0_0.py
setup.py

[FIX - Failing test](https://jira.extge.co.uk/browse/IP-1860)
==========
* One test on master and develop is failing:
```
======================================================================
FAIL: test_migrate_reported_variant (protocols.tests.test_migration.test_migration_reports_5_0_0_to_reports_6_0_0.TestMigrateInterpretedGenome5To6)
Traceback (most recent call last):
File "/gel/GelReportModels/protocols/tests/test_migration/test_migration_reports_5_0_0_to_reports_6_0_0.py", line 133, in test_migrate_reported_variant
self.assertEqual(new, MigrateReports500To600().migrate_report_event(report_event=old))
AssertionError: <protocols.reports_6_0_0.ReportEvent object at …
```

FIX - Failing test

---

protocols/migration/migration_reports_4_0_0_to_reports_3_0_0.py
protocols/protocol.py
protocols/tests/test_migration/test_migration_reports_4_0_0_to_reports_3_0_0.py

[IP-1993 - Migrate EQ RD from 4 to 3](https://jira.extge.co.uk/browse/IP-1993)
=========
* `migrateJsonDict` now ignores underscores together with casing, effectively transforming snake case to camel case and vice versa
* The `key_mapper` in `migrateJsonDict` is now recursively applied down the hierarchy of objects

IP-1993 - Migrate EQ RD from 4 to 3

---

protocols/migration/base_migration.py
protocols/migration/migration_reports_4_0_0_to_reports_5_0_0.py
protocols/migration/migration_reports_6_0_0_to_reports_5_0_0.py
protocols/tests/test_migration/test_migration_reports_6_0_0_to_reports_5_0_0.py
schemas/IDLs/org.gel.models.report.avro/5.0.0/ExitQuestionnaire.avdl
schemas/IDLs/org.gel.models.report.avro/6.0.0/ExitQuestionnaire.avdl

* Generic method to convert lists of things in `BaseMigration.migrate_list_of_things()`. In subsequent PRs we should get rid of all the by list methods

Ip 2021/eq cancer migration 6 to 5

---

CHANGES.md
protocols/migration/base_migration.py
protocols/migration/migration_helpers.py
protocols/migration/migration_reports_210_to_reports_300.py
protocols/migration/migration_reports_300_to_reports_400.py
protocols/migration/migration_reports_400_to_reports_300.py
protocols/migration/migration_reports_400_to_reports_500.py
protocols/migration/migration_reports_500_to_reports_400.py
protocols/migration/migration_reports_500_to_reports_600.py
protocols/migration/migration_reports_600_to_reports_500.py
protocols/protocol.py
protocols/tests/test_migration/base_test_migration.py
protocols/tests/test_migration/test_migration_reports_300_to_reports_400.py
protocols/tests/test_migration/test_migration_reports_500_to_reports_300.py
protocols/tests/test_migration/test_migration_reports_500_to_reports_400.py
protocols/tests/test_migration/test_migration_reports_500_to_reports_600.py
protocols/tests/test_migration/test_migration_reports_600_to_reports_500.py
protocols_utils/utils/abstract_migration_test_real_data.py
protocols_utils/utils/migration_test_real_data_cancer.py
protocols_utils/utils/migration_test_real_data_rd.py
setup.py

* Improve performance of migrations by:
- Avoid unnecessary validations
- Improve performance of `toJsonDict()`
- Avoid calling `fromJsonDict()` recursively
* Fix some issues checking equality of cancer actions in round trip migrations
* In `MigrationHelpers` choice the right version when an entity validates against multiple version by looking at the version control

More on migrations (v7.1.10)

---

protocols/tests/test_migration/test_migration_helpers.py

These tests are failing on develop.
The source of the error is that (for some reason I can't quite figure out) when run as an individual test, the nullable fields are all filled when `fill_nullables` is set to `True`. However, when run as a whole, these two tests don't have their nullables filled. In the interest of getting this released I'll make a ticket for fixing the mock object generation at a later date.

Fix - Failing tests

---

setup.py

See https://pyyaml.org/wiki/PyYAML#history

Bump PyYAML version for Python 3.7 compatibility

---

schemas/IDLs/org.gel.models.report.avro/6.0.0/CommonInterpreted.avdl

There is an equivalent change in biotools that will mean we can remove this in the next version.

Hacky fix to data model name clash

---

setup.py

Fix pyyaml secutiry issue here:
https://github.com/genomicsengland/GelReportModels/network/alert/setup.py/pyyaml/open

Fix - PyYaml security issue

---

.gitlab-ci.yml

It failed last time because of this and should not be needed any more

Remove profile from gitlab config

---

pom.xml
schemas/IDLs/org.gel.models.metrics.avro/1.2.1/FamilySelection.avdl
setup.py

* Map is not supported as a type in OpenCGA, so use array/list instead
* Added extra flag enum value to FamilySelection also
* Bump version to 7.3.4

Use list for selection events in FamilySelection

---

pom.xml
schemas/IDLs/org.gel.models.report.avro/6.1.0/ClinicalReport.avdl
setup.py

- Removes Interpreted Genome Version from AdditionalFindingsClinicalReport model
- Bumps version from 7.5.1 --> 7.5.2

fix: removes ig version from af clinical report model

---

builds.json
pom.xml
protocols/resources/builds.json
protocols/tests/test_util/test_dependency_manager.py
protocols/util/dependency_manager.py
schemas/IDLs/org.gel.models.cva.avro/1.5.2/Comment.avdl
schemas/IDLs/org.gel.models.cva.avro/1.5.2/CvaEvidence.avdl
schemas/IDLs/org.gel.models.cva.avro/1.5.2/CvaVariant.avdl
schemas/IDLs/org.gel.models.cva.avro/1.5.2/DataIntake.avdl
schemas/IDLs/org.gel.models.cva.avro/1.5.2/ObservedVariant.avdl
schemas/IDLs/org.gel.models.cva.avro/1.5.2/ReportEvent.avdl
schemas/IDLs/org.gel.models.cva.avro/1.5.2/Transactions.avdl
schemas/IDLs/org.gel.models.report.avro/6.2.0/ClinicalReport.avdl
schemas/IDLs/org.gel.models.report.avro/6.2.0/CommonInterpreted.avdl
schemas/IDLs/org.gel.models.report.avro/6.2.0/CommonRequest.avdl
schemas/IDLs/org.gel.models.report.avro/6.2.0/ExitQuestionnaire.avdl
schemas/IDLs/org.gel.models.report.avro/6.2.0/InterpretationRequestCancer.avdl
schemas/IDLs/org.gel.models.report.avro/6.2.0/InterpretationRequestRD.avdl
schemas/IDLs/org.gel.models.report.avro/6.2.0/InterpretedGenome.avdl
schemas/IDLs/org.gel.models.report.avro/6.2.0/MDTDeliveryProtocol.avdl
schemas/IDLs/org.gel.models.report.avro/6.2.0/ReportVersionControl.avdl
schemas/IDLs/org.gel.models.report.avro/6.2.0/VariantInterpretationLog.avdl
setup.py

Adding field for no evidences as detailed in https://jira.extge.co.uk/browse/GRM-29
The new feature is added in this commit: https://github.com/genomicsengland/GelReportModels/commit/fd29eaebf9acf051d1dbea1e52680fb06c0227c8
CVA models depend on reports so had to create a new version of these too (1.5.2), but this contains no changes.
There are other changes to be made in the same epic (https://jira.extge.co.uk/browse/GRM-38), so keeping everything in separate branch for now
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/genomicsengland/gelreportmodels/521)

GRM-29 - Variant Interpretation Log no Evidence field
